[project]
name = "local-ai-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shah", email = "mszaibi007@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ollama>=0.6.3",
    "streamlit>=1.64.0",
]

[project.scripts]
local-ai-chatbot = "local_ai_chatbot:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
